### ISSUE TITLE
Plugin ignores the layout grid offset setting

### ISSUE THREAD

**Issue by elaltito** [KevinvBre/Align-and-resize-to-layout#3]
Hello, greeeeeat plugin! Have been looking for something exactly like it for a while. It works perfectly however the only issue is that the plugin seems to ignore the grid offset setting in Sketch's layout setting. Is there any way to fix this?

**Comment by Nivekvb** [comment]
Tyvm, it takes the offset value into account but only when the layout is centered on the page. The current Sketch API version doesn't support it. (yet). So, nope sorry. 

Thanks for your using the plugin though! I'll put a few notes in the github page.
- Kevin

**Comment by elaltito** [comment]
ah ok I see, thanks for getting back to me. Shame about the API support, fingers crossed for the future ! ;)

Just and idea – but I am not a developer so maybe this doesn't make sense – but is there no way to just get the current offset value of the layout on the active artboard (for example 120px) and just add that amount to the align output value dynamically? So it would be : "Align as usual -> Add 120px"
